name: Deploy React APP to GCP

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use google cloud library
        uses: google-github-actions/setup-gcloud@v2.1.1
        with:
          project_id: ${{ secrets.GCE_PROJECT_ID }} 
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate Google Cloud             
        uses: google-github-actions/auth@v2    
        with: 
          credentials_json: '${{ secrets.GCP_SA_KEY }}' 

      - name: Configure Docker
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/personal-gcp-new/test-chat-fe-app --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} .

      - name: Push docker image
        run: |
          docker push gcr.io/personal-gcp-new/test-chat-fe-app:latest

      - name: Deploy to GCP
        run: |
          gcloud run deploy test-chat-fe-app-web \
          --image gcr.io/personal-gcp-new/test-chat-fe-app:latest \
          --platform managed \
          --region asia-southeast1 \
          --allow-unauthenticated --set-env-vars REACT_APP_API_URL=${{secrets.REACT_APP_API_URL}}

      
      